_core:
  default_config_hash: q2QxaHH2DKzN8zFKH4sBu5eWpPMNQERApyo7cDmngt4
langcode: en-gb
path_type: path
path: /themes/custom/petersfieldpilates/favicons
tags:
  - '<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">'
  - '<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">'
  - '<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">'
  - '<link rel="manifest" href="/site.webmanifest">'
  - '<meta name="msapplication-TileColor" content="#61993c">'
  - '<meta name="theme-color" content="#ffffff">'
remove_default: 1
